package com.photosoap.ui.theme

import androidx.compose.ui.graphics.Color

// M3 Dynamic Color is primary, but we define fallbacks

val md_theme_light_primary = Color(0xFF3859A4)
val md_theme_light_onPrimary = Color(0xFFFFFFFF)
val md_theme_light_primaryContainer = Color(0xFFDAE2FF)
val md_theme_light_onPrimaryContainer = Color(0xFF001847)
val md_theme_light_secondary = Color(0xFF585E71)
val md_theme_light_onSecondary = Color(0xFFFFFFFF)
val md_theme_light_secondaryContainer = Color(0xFFDDE1F9)
val md_theme_light_onSecondaryContainer = Color(0xFF151B2C)
val md_theme_light_tertiary = Color(0xFF735572)
val md_theme_light_onTertiary = Color(0xFFFFFFFF)
val md_theme_light_tertiaryContainer = Color(0xFFFED7FA)
val md_theme_light_onTertiaryContainer = Color(0xFF2B122C)
val md_theme_light_error = Color(0xFFBA1A1A)
val md_theme_light_background = Color(0xFFF9F9FF)
val md_theme_light_onBackground = Color(0xFF191C20)
val md_theme_light_surface = Color(0xFFF9F9FF)
val md_theme_light_onSurface = Color(0xFF191C20)
val md_theme_light_surfaceVariant = Color(0xFFE1E2EC)
val md_theme_light_onSurfaceVariant = Color(0xFF44474F)

val md_theme_dark_primary = Color(0xFFB1C5FF)
val md_theme_dark_onPrimary = Color(0xFF002A6E)
val md_theme_dark_primaryContainer = Color(0xFF1E418B)
val md_theme_dark_onPrimaryContainer = Color(0xFFDAE2FF)
val md_theme_dark_secondary = Color(0xFFC1C6DD)
val md_theme_dark_onSecondary = Color(0xFF2A3042)
val md_theme_dark_secondaryContainer = Color(0xFF414659)
val md_theme_dark_onSecondaryContainer = Color(0xFFDDE1F9)
val md_theme_dark_tertiary = Color(0xFFE1BBDD)
val md_theme_dark_onTertiary = Color(0xFF422742)
val md_theme_dark_tertiaryContainer = Color(0xFF5A3D59)
val md_theme_dark_onTertiaryContainer = Color(0xFFFED7FA)
val md_theme_dark_error = Color(0xFFFFB4AB)
val md_theme_dark_background = Color(0xFF191C20)
val md_theme_dark_onBackground = Color(0xFFE2E2E8)
val md_theme_dark_surface = Color(0xFF191C20)
val md_theme_dark_onSurface = Color(0xFFE2E2E8)
val md_theme_dark_surfaceVariant = Color(0xFF44474F)
val md_theme_dark_onSurfaceVariant = Color(0xFFC4C6D0)

// Functional colors
val Green = Color(0xFF4CAF50)
val Red = Color(0xFFE53935)
val Orange = Color(0xFFFF9800)
val Yellow = Color(0xFFFFC107)
val Purple = Color(0xFF9C27B0)
val Mint = Color(0xFF4DB6AC)
